name: media_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^10.0.0
  just_audio: ^0.9.36
  audio_service: ^0.18.9
  path_provider: ^2.1.3
  audio_session: ^0.1.18
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  background_image: "assets/splash.png"
  android_12:
    image: null
    color: "#53027C"
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fast-forward.png
    - assets/pause.png
    - assets/play-button-arrowhead.png
    - assets/previous.png
    - assets/upload.png
    - assets/album_art.png
